name: YAML Lint

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
